module.exports = {

  about: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    // {
    //   type: 'link',
    //   href: '/showcase',
    //   label: 'Showcase',
    // },
    // {
    //   type: 'link',
    //   href: '/feedback',
    //   label: 'Feedback',
    // },
    // {
    //   type: 'link',
    //   label: 'Chat with us on Discord',
    //   href: 'https://discord.gg/docusaurus',
    // },
  ],
};
